export const CURATED_WORDS = {
  // === 4 LETTERS ===
  4: [
    // Git / workflow
    'FORK',
    'PULL',
    'PUSH',
    'HEAD',
    'DIFF',
    'REPO',
    'SPEC',
    'MOCK',
    'STUB',
    'DEMO',
    'BETA',
    'PROD',
    // Langages / runtimes
    'RUST',
    'PERL',
    'JAVA',
    'BASH',
    'YAML',
    'JSON',
    'HTML',
    'SASS',
    'RUBY',
    'DART',
    'GLSL',
    'AJAX',
    // Concepts
    'BYTE',
    'BOOL',
    'ENUM',
    'LOOP',
    'NULL',
    'VOID',
    'TRUE',
    'HEAP',
    'CODE',
    'DATA',
    'TYPE',
    'ARGS',
    'VARS',
    'CHAR',
    'LONG',
    'CASE',
    'ELSE',
    'GOTO',
    'PROC',
    'BITS',
    'MASK',
    // Réseau / Unix
    'PING',
    'GREP',
    'CURL',
    'PORT',
    'HOST',
    'LINK',
    'NODE',
    'ROOT',
    'UNIX',
    'DISK',
    'FILE',
    'PATH',
    'USER',
    'SUDO',
    'BAUD',
    'GATE',
    'WIRE',
    'CHIP',
    // Data / IO
    'HASH',
    'TREE',
    'LIST',
    'POST',
    'BLOB',
    'GLOB',
    'READ',
    'SAVE',
    'SEEK',
    'DUMP',
    'SWAP',
    'WRAP',
    // Autres
    'CRON',
    'FLAG',
    'LOCK',
    'PIPE',
    'MAKE',
    'TEST',
    'EXIT',
    'KILL',
    'PASS',
    'FAIL',
  ],

  // === 5 LETTERS ===
  5: [
    // Langages / frameworks
    'REACT',
    'REDUX',
    'SWIFT',
    'LINUX',
    'REDIS',
    'NGINX',
    'SCALA',
    'EMACS',
    'CMAKE',
    'MAVEN',
    'FLASK',
    'RAILS',
    'BISON',
    // Git / workflow
    'MERGE',
    'CLONE',
    'STASH',
    'BLAME',
    'PATCH',
    // Concepts fondamentaux
    'ARRAY',
    'STACK',
    'QUEUE',
    'CACHE',
    'CLASS',
    'CONST',
    'FLOAT',
    'BUILD',
    'DEBUG',
    'FETCH',
    'PARSE',
    'SLICE',
    'QUERY',
    'PROXY',
    'TUPLE',
    'LOGIC',
    'MACRO',
    'GRAPH',
    'FRAME',
    'ROUTE',
    'BATCH',
    'FIELD',
    'VALUE',
    'ENTRY',
    'EVENT',
    // Contrôle de flux
    'WHILE',
    'BREAK',
    'YIELD',
    'PRINT',
    'INPUT',
    // Async / concurrence
    'ASYNC',
    'AWAIT',
    'MUTEX',
    // Réseau / sécurité
    'TOKEN',
    'HTTPS',
    // Data
    'BYTES',
    'MODEL',
    'INDEX',
    'TABLE',
    'UNION',
    // Erreurs / debug
    'THROW',
    'CATCH',
    'TRACE',
    'PANIC',
    // Hardware / OS
    'PIXEL',
    'CHIPS',
    // Autres
    'REGEX',
    'SCOPE',
    'SHELL',
    'SLEEP',
    'CHMOD',
  ],

  // === 6 LETTERS ===
  6: [
    // Git
    'COMMIT',
    'BRANCH',
    'REBASE',
    'REMOTE',
    'ORIGIN',
    // Concepts
    'RETURN',
    'LAMBDA',
    'OBJECT',
    'STRING',
    'STRUCT',
    'VECTOR',
    'BINARY',
    'BUCKET',
    'CURSOR',
    'MODULE',
    'METHOD',
    'SCHEMA',
    'STATIC',
    'PUBLIC',
    'IMPORT',
    'EXPORT',
    'INVOKE',
    'HANDLE',
    'ATOMIC',
    'OPCODE',
    'PARSER',
    'GETTER',
    'SETTER',
    'RANDOM',
    'LOOKUP',
    // SQL / data
    'DELETE',
    'INSERT',
    'UPDATE',
    'SELECT',
    'ENCODE',
    'DECODE',
    'ASSERT',
    'OUTPUT',
    'STREAM',
    'NUMBER',
    'DOUBLE',
    'SWITCH',
    'COLUMN',
    'ENTITY',
    'SEARCH',
    'RENAME',
    // Async / concurrence
    'THREAD',
    'FUTURE',
    'SIGNAL',
    // Réseau
    'PACKET',
    'ROUTER',
    'SOCKET',
    'SERVER',
    'CLIENT',
    'COOKIE',
    'HEADER',
    'CONFIG',
    'DEPLOY',
    'MEMORY',
    // Outils / écosystème
    'DOCKER',
    'GITHUB',
    'GITLAB',
    'DEVOPS',
    'GRADLE',
    'PLUGIN',
    'WIDGET',
    'LAPTOP',
    'GADGET',
    // OS / système
    'KERNEL',
    'DAEMON',
    'BUFFER',
    'SYNTAX',
    'SCRIPT',
    'BACKUP',
    'PYTHON',
    // Debug
    'LOGGER',
    'LINKER',
    'ESCAPE',
    // Data
    'RECORD',
    'FILTER',
    'REDUCE',
  ],

  // === 7 LETTERS ===
  7: [
    'PROGRAM',
    'COMPILE',
    'EXECUTE',
    'CONSOLE',
    'COMMAND',
    'BOOLEAN',
    'INTEGER',
    'DECIMAL',
    'PAYLOAD',
    'REQUEST',
    'REFRESH',
    'REPLACE',
    'DEFAULT',
    'CONTEXT',
    'PRIVATE',
    'FOREACH',
    'PACKAGE',
    'VERSION',
    'RELEASE',
    'WEBPACK',
    'ROUTING',
    'BACKEND',
    // Langages
    'HASKELL',
    'FORTRAN',
    'CLOJURE',
    // Concepts
    'ANDROID',
    'BITCOIN',
    'NETWORK',
    'PROCESS',
    'THREADS',
    'VIRTUAL',
    'PROMISE',
    'ITERATE',
    'GENERIC',
    'LIBRARY',
    'BINDING',
    'BUILDER',
    'HANDLER',
    'WRAPPER',
    'CLEANUP',
    'TESTING',
    'LOGGING',
    'STORAGE',
    'GATEWAY',
    'CLUSTER',
    'MACHINE',
    'CAPTURE',
    'RUNTIME',
    'DECLARE',
    'DESTROY',
    'EXTENDS',
    'EXPLODE',
    'INHERIT',
    'KEYWORD',
    'LITERAL',
    'OPERAND',
    'POINTER',
    'RECURSE',
    'SESSION',
    'TYPEDEF',
    'UNICODE',
    'UTILITY',
  ],

  // === 8 LETTERS ===
  8: [
    'FUNCTION',
    'VARIABLE',
    'DATABASE',
    'FRONTEND',
    'TERMINAL',
    'KEYBOARD',
    'SNAPSHOT',
    'REGISTRY',
    'SEGFAULT',
    'PIPELINE',
    'CALLBACK',
    'INSTANCE',
    'RESPONSE',
    'ITERATOR',
    'DOCUMENT',
    'SECURITY',
    'ENCODING',
    'FIREWALL',
    'POINTERS',
    'LISTENER',
    'ABSTRACT',
    'COMPILER',
    'DEBUGGER',
    'TEMPLATE',
    'OVERFLOW',
    'OPERATOR',
    'PROPERTY',
    'ARGUMENT',
    'COMPUTER',
    'HARDWARE',
    'SOFTWARE',
    'PASSWORD',
    'USERNAME',
    'ENDPOINT',
    'METADATA',
    'RESOLVER',
    'PROVIDER',
    'RENDERER',
    'DELEGATE',
    'KEYWORDS',
    'MUTATION',
    'REDUCERS',
    'PROTOCOL',
    'ASSEMBLY',
    'COMPRESS',
    'DOWNLOAD',
    'FRAGMENT',
    'HOSTNAME',
    'INTERNET',
    'RELATION',
    'TRAVERSE',
    'ETHERNET',
  ],

  // === 9 LETTERS ===
  9: [
    'ALGORITHM',
    'INTERFACE',
    'COMPONENT',
    'RECURSION',
    'PARAMETER',
    'EXCEPTION',
    'FRAMEWORK',
    'NAMESPACE',
    'DECORATOR',
    'COROUTINE',
    'BENCHMARK',
    'ATTRIBUTE',
    'PRIMITIVE',
    'EXECUTION',
    'SEMAPHORE',
    'CONTAINER',
    'INTERPRET',
    'ITERATION',
    'RECURSIVE',
    'REFERENCE',
    'SINGLETON',
    'STRUCTURE',
    'TIMESTAMP',
    'TRANSPILE',
    'VALIDATOR',
    'WHITELIST',
    'BLACKLIST',
    'BLUEPRINT',
    'BROADCAST',
    'DEBUGGING',
    'ENCRYPTED',
    'FORMATTER',
    'FUNCTIONS',
    'LOCALHOST',
    'PROTOTYPE',
    'VARIABLES',
    'PROCESSOR',
    'EXTENSION',
  ],

  // === 10 LETTERS ===
  10: [
    'TYPESCRIPT',
    'JAVASCRIPT',
    'PARAMETERS',
    'ENCRYPTION',
    'MIGRATIONS',
    'CONTROLLER',
    'MIDDLEWARE',
    'REPOSITORY',
    'DEPLOYMENT',
    'DICTIONARY',
    'ALGORITHMS',
    'INTERFACES',
    'EXCEPTIONS',
    'REFLECTION',
    'PROCESSORS',
    'KUBERNETES',
    'CONCURRENT',
    'ASSERTIONS',
    'ATTRIBUTES',
    'COMPONENTS',
    'NAMESPACES',
    'PRECEDENCE',
    'STRUCTURES',
    'THROUGHPUT',
    'VALIDATION',
    'EXTENSIONS',
    'PRIMITIVES',
    'SERIALIZER',
    'SUBROUTINE',
    'FRAMEWORKS',
    'GENERATORS',
    'PROPERTIES',
  ],
} as const;

export function getFlatCuratedWords(): { word: string; length: number }[] {
  const flat: { word: string; length: number }[] = [];

  for (const [lengthKey, words] of Object.entries(CURATED_WORDS)) {
    const expectedLength = Number(lengthKey);

    for (const word of words) {
      if (word.length !== expectedLength) {
        console.warn(
          `The word “${word}” is misclassified: it is in the ${expectedLength} bucket, but its actual length is ${word.length}`,
        );
        continue;
      }
      flat.push({ word, length: word.length });
    }
  }

  const unique = Array.from(new Map(flat.map((w) => [w.word, w])).values());

  return unique;
}
